apiVersion: v2
name: edumfa
description: A Helm chart for eduMFA
icon: https://raw.githubusercontent.com/eduMFA/eduMFA/main/doc/_static/images/edumfa-icon.png
type: application

version: SET_BY_CI
# TODO set to 2.10.0 on v1.0.0
appVersion: ""
