{{- if .Values.edumfa.challengeCleanup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "edumfa.fullname" . }}-challenge-cronjob
spec:
  schedule: {{ required "A CronJob schedule is required for challenge cleanup." .Values.edumfa.challengeCleanup.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          {{- with .Values.edumfa.challengeCleanup.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        spec:
          restartPolicy: OnFailure
          {{- $command := list "edumfa-token-janitor" "cleanupchallenges" }}
          {{- $spec_settings := dict "command" $command}}
          {{- $spec_params := dict "Chart" .Chart "Values" .Values "specSettings" $spec_settings "specValues" .Values.edumfa.challengeCleanup }}
          {{- include "edumfa.spec" $spec_params | nindent 10}}
{{- end }}
